#!/usr/bin/env bash
# harness-launcher.sh — thin wrapper that delegates to the shared harness.
# Generated by coordination/harness/core/bootstrap.sh. Do not edit by hand;
# re-run bootstrap to refresh.
set -euo pipefail

COORDINATION="${HARNESS_COORDINATION:-/Users/alejandrocruz/WebstormProjects/guachinches-coordination}"
PROFILE="mobile"

# Run from the consumer repo root so Claude picks up its .mcp.json.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export HARNESS_REPO_ROOT="$(pwd)"

exec "${COORDINATION}/harness/core/run.sh" --profile "${PROFILE}" "$@"
